name: Node.js CI

on:
  push:
    branches:
      - main  # O workflow será executado em pushes no branch principal
  pull_request:
    branches:
      - main  # Também será executado quando um pull request for feito para o branch principal

jobs:
  build:
    runs-on: ubuntu-latest  # O processo será executado em uma máquina virtual com Ubuntu

    steps:
    - name: Checar o código do repositório
      uses: actions/checkout@v2  # Faz o checkout do código do repositório

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Escolha a versão que seu projeto utiliza

    - name: Navegar até o diretório do cliente
      run: cd client && npm install  # Instala as dependências na pasta 'client'

    - name: Rodar os testes no cliente
      run: cd client && npm test  # Roda os testes no diretório 'client'

    - name: Navegar até o diretório do servidor
      run: cd server && npm install  # Instala as dependências na pasta 'server'

    - name: Rodar os testes no servidor
      run: cd server && npm test  # Roda os testes no diretório 'server'
